name: Bench Validation

permissions:
  contents: write

on:
  push:
    branches:
      - '*'
      - '**'

jobs:
  run-bench:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Commit Message
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "Latest commit message: $commit_message"
          if echo "$commit_message" | grep -iE '^bench[[:space:]]+[0-9]+$|^bench:[[:space:]]*[0-9]+$'; then
            echo "Bench already included in last commit. Skipping job."
            exit 0
          fi

      - name: Set up C++ compiler and CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Build and Run Bench
        run: |
          cd openbench
          make EXE=illumina
          output=$(./illumina bench)
          bench_nodes=$(echo "$output" | grep -o '^[0-9]*' | head -n 1)
          echo "$bench_nodes" > bench.txt

      - name: Verify Bench File and Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          bench_message=$(cat openbench/bench.txt)
          echo $(date) >> openbench/bench.txt
          git add openbench/bench.txt
          git commit -m "bench $bench_message"
          git push
